title = "DocumentService"
gitRepoUrl = "https://github.com/anthony0br/DocumentService" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = [
    "DocumentService",
    "DocumentStore",
    "Document",
    "SaveUtil",
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright Â© 2024 Anthony O'Brien. Built with Moonwave and Docusaurus"
